
//Get All users 
###
GET http://localhost:4000/api/users/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiYWRtaW4iLCJsYXN0TmFtZSI6Im1hbmFnZXIiLCJ1c2VyVHlwZSI6ImFkbWluIiwiZXhwIjoxNzUyMjI5Mzc5LCJpYXQiOjE3NTIyMjU3Nzl9.f7ifLrGOdh-mS_bC-D3-7OpcMhvOW4byWOjoKOqYXSk

//Get user by id
###
GET http://localhost:4000/api/users/2

###
GET http://localhost:4000/api/bookings/my/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImVtYWlsIjoiZmVsbG9AZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiZmVsaXgiLCJsYXN0TmFtZSI6ImtpYmV0IiwidXNlclR5cGUiOiJtZW1iZXIiLCJleHAiOjE3NTI2NTk1MzgsImlhdCI6MTc1MjY1NTkzOH0.6SkTXsLVGiVZSg0HFTTlxQVZLfEDEfVyHq8UUnp04oo

//Create new user
###
POST http://localhost:4000/api/users/
Authorization: 
Content-Type: application/json

{
    "firstName": "kelvin",
    "lastName": "Kimtai",
    "email": "kelvin@gmail.com",
    "contactPhone": "0716037570",
    "address":"123005",
    "userType": "member",
    "password":"1234"
}

//Update user by id
###
PUT http://localhost:4000/api/users/1
Authorization: 
Content-Type: application/json

{
    "firstName": "Newton",
    "lastName": "Koskei",
    "email": "henry@gmail.com",
    "contactPhone": "0712037576",
    "address":"123455",
    "userType": "member",
    "password":"1234"
}

//Delete user by id
###
DELETE http://localhost:4000/api/users/2
Authorization: 


//Register user
###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "firstName": "admin",
  "lastName": "manager",
  "email": "admin@gmail.com",
  "password": "admin1234",
  "contactPhone": "0716037571",
  "address":"1220005",
  "userType": "admin"
}

###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "firstName": "admin",
  "lastName": "manage",
  "email": "admin@gmail.com",
  "password": "admin123",
  "contactPhone": "0717037500",
  "address":"1220005",
  "userType": "admin"
}

//Login user
###
POST http://localhost:4000/api/auth/login
content-type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin123"
}
###
POST http://localhost:4000/api/auth/login
content-type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin1234"
}

// 2. Endpoints for Hotel

//Get All Hotels 
###
GET http://localhost:4000/api/hotels/

//Get Hotel by id 
###
GET http://localhost:4000/api/hotels/2

//Create new Hotel
###
POST http://localhost:4000/api/hotels/
Content-Type: application/json

{
  "name": "Ocean View Resort",
  "location": "Mombasa",
  "address": "Thika Road, Nairobi, Kenya",
  "contactPhone": "+254712345678",
  "category": "5-star",
  "rating": 5,
  "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
  "priceRange": "$150 - $300",
  "amenities": [
    "Free WiFi",
    "Swimming Pool",
    "Gym",
    "Spa",
    "Restaurant",
    "Conference Rooms"
  ]
}


//Update Hotel by id 
###
PUT http://localhost:4000/api/hotels/2
Content-Type: application/json

{
  "name": "Ocean View Resort",
  "location": "Mombasa",
  "address": "Thika Road, Nairobi, Kenya",
  "contactPhone": "+254712345678",
  "category": "4-star",
  "rating": 5,
  "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
  "priceRange": "$150 - $300",
  "amenities": [
    "Free WiFi",
    "Swimming Pool",
    "Gym",
    "Spa",
    "Restaurant",
    "Conference Rooms"
  ]
}

//Delete Hotel by id
###
DELETE http://localhost:4000/api/hotels/1

// 3. Endpoints for Room

//Get All Rooms 
###
GET http://localhost:4000/api/rooms/

//Get Room by id 
###
GET http://localhost:4000/api/rooms/1

//Create new Room
###
POST http://localhost:4000/api/rooms/
Content-Type: application/json

{
  "hotelId": 1,
  "roomType": "Standard Room",
  "pricePerNight": 120.50,
  "capacity": 3,
  "amenities": ["wifi", "air conditioning", "balcony"],
  "isAvailable": true,
  "description": "A spacious deluxe suite with sea view and private balcony.",
  "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREpk8q4HABvDAZ7Fb8P4Ri_3BrApiC_2ZZ8XOpoPpoAacaU9QyZWj-ogI&s"
}


//Update Existing Room by id
###
PUT http://localhost:4000/api/rooms/3
Content-Type: application/json

{
  "hotelId": 1,
  "roomType": "Deluxe Suite",
  "pricePerNight": 120.50,
  "capacity": 3,
  "amenities": ["wifi", "air conditioning", "balcony"],
  "isAvailable": true,
  "description": "A spacious deluxe suite with sea view and private balcony."
}


//Delete Room by id
###
DELETE http://localhost:4000/api/rooms/4

//3. Endpoints for Booking
//Get All Booking 
###
GET http://localhost:4000/api/bookings

//Get Booking by id 
###
GET http://localhost:4000/api/bookings/2

//Create new Booking
###
POST http://localhost:4000/api/bookings/
Content-Type: application/json

{
  "userId": 12,
  "roomId": 3,
  "checkInDate": "2025-07-10T14:00:00Z",
  "checkOutDate": "2025-07-12T10:00:00Z",
  "totalAmount": "1500.00",
  "bookingStatus": "Pending"
}

//Create new Booking
###
PUT http://localhost:4000/api/bookings/3
Content-Type: application/json

{
  "userId": 4,
  "roomId": 8,
  "checkInDate": "2025-07-10T14:00:00Z",
  "checkOutDate": "2025-07-12T10:00:00Z",
  "totalAmount": "1400.00",
  "bookingStatus": "Pending"
}

###
PUT http://localhost:4000/api/bookings/cancel/9

//Delete Booking by id
###
DELETE http://localhost:4000/api/bookings/4

//5. Endpoints for Payment

//Get All Payments
###
GET http://localhost:4000/api/payments

//Get Payments by id 
###
GET http://localhost:4000/api/payments/1

//Create new Payments
###
POST http://localhost:4000/api/payments/
Content-Type: application/json

{
  "bookingId": 2,
  "amount": "6000.00",
  "paymentMethod": "Mpesa",
  "transactionId": "MP123456789",
  "paymentStatus": "Completed",
  "paymentDate": "2025-07-01T12:30:00z"
}

//Create new Payments
###
PUT http://localhost:4000/api/payments/2
Content-Type: application/json

{
  "bookingId": 2,
  "amount": "4000.00",
  "paymentMethod": "Mpesa",
  "transactionId": "MP123456755",
  "paymentStatus": "Completed",
  "paymentDate": "2025-07-01T12:30:00z"
}

//Delete payment by id
###
DELETE http://localhost:4000/api/payments/3

//6. Endpoints for Tickets

//Get All tickets
###
GET http://localhost:4000/api/tickets

//Get ticket by id 
###
GET http://localhost:4000/api/tickets/2

//Create new tickets
###
POST http://localhost:4000/api/tickets/
Content-Type: application/json

{
  "userId": 4,
  "subject": "Request for refund",
  "description": "I canceled my reservation two days ago and have not yet received the refund.",
  "status": "Resolved"
}

//Update existing  tickets
###
PUT http://localhost:4000/api/tickets/4
Content-Type: application/json

{
  "userId": 4,
  "subject": "Request for refund",
  "description": "I canceled my reservation two days ago and have not yet received the refund.",
  "status": "Open"
}

//DELETE existing  tickets
###
DELETE http://localhost:4000/api/tickets/4






